### ISSUE TITLE
Error while sending a request with Content-Type set to `application/vnd.api+json`

### ISSUE THREAD

**Issue by Rxbsxn** [klerick/nestjs-json-api#10]
Hello dear maintainers - Tonight I was playing around with your JSON-API package and Ember.js.
While creating a record from Ember.js applicationm, Ember sets `Content-Type` to be `application/vnd.api+json` to the request. Unfortunately, the application is not accepting this header. When I copied the whole body of the request and use it in Postman with Content-Type header set to `application/json` everything works as it should. Please see the screen
![image](https://user-images.githubusercontent.com/17426143/200420524-00c1366f-019a-4023-bb1c-3a35890e25ce.png)

**Comment by klerick** [comment]
Hi, I believe it is problem of ```body-parser```
https://github.com/expressjs/body-parser/issues/131

try to do like this:
```
import { NestFactory } from '@nestjs/core';
import * as bodyParser from 'body-parser';
import { AppModule } from './app/app.module';
const app = await NestFactory.create(AppModule);
app.use(bodyParser.json({ type: 'application/vnd.api+json' }));
```
