### ISSUE TITLE
[Monorepo] Separate package for each application

### ISSUE THREAD

**Issue by kun391** [klerick/nestjs-json-api#11]
Hi, I really like this one.

Is this project the example or the template for the package Jsonapi in Nestjs and Client (React, Angular, ...)?

I think if this project is a separate package.json for each application may be good.
In my mind, It helps me to easy to maintenance, move or drop applications, ...
We can use pnpm + turborepo

**Comment by klerick** [comment]
you can find example for main and client(angular and react) lib [here](https://github.com/klerick/nestjs-json-api/tree/master/apps). 

this is part of repo but not is package. this structure for me more simple. it is easyly in during maintained. 

I dont use pnpm. but I will try to investigate it and will try to make your life easier)
