### ISSUE TITLE
TypeError: metatype is not a constructor

### ISSUE THREAD

**Issue by kun391** [klerick/nestjs-json-api#15]
Hi there, 

I implemented this version `"json-api-nestjs": "^4.2.0"` but I'm getting this error 
`TypeError: metatype is not a constructor`,

I trying this one. It will occur the error
```
import { Module } from "@nestjs/common";
import { JsonApiModule } from "json-api-nestjs";
import { Examples } from "../entities/example.entity";

@Module({
  imports: [
  JsonApiModule.forRoot({
    entities: [Examples],
      options: {
        debug: true,
        maxExecutionTime: 3000,
        requiredSelectField: false,
      },
  }),
  ],
})
export class ResourcesModule {}
```

I tried to remove the Examples entity, will run without the error
```
import { Module } from "@nestjs/common";
import { JsonApiModule } from "json-api-nestjs";
import { Examples } from "../entities/example.entity";

@Module({
  imports: [
  JsonApiModule.forRoot({
    entities: [Examples],
      options: {
        debug: true,
        maxExecutionTime: 3000,
        requiredSelectField: false,
      },
  }),
  ],
})
export class ResourcesModule {}
```

Could you please tell me if I losing the config somewhere?

**Comment by klerick** [comment]
do you import tyoeorm? like this https://github.com/klerick/nestjs-json-api/blob/master/apps/example/src/app/app.module.ts#L9

**Comment by kun391** [comment]
> do you import tyoeorm? like this https://github.com/klerick/nestjs-json-api/blob/master/apps/example/src/app/app.module.ts#L9

@klerick: Yes, I imported in the app module

**Comment by klerick** [comment]
could you create repo with code which have error. I will try to help find solutions.

**Comment by kun391** [comment]
```
  ...{
    entities: [Roles, Comments, Users, Addresses, BookList],
  },
};

```
https://github.com/klerick/nestjs-json-api/blob/master/libs/database/src/lib/config.ts#L7

I missing defined the entities like that @klerick
