### ISSUE TITLE
[Question] How can I overrided the resource name?

### ISSUE THREAD

**Issue by kun391** [klerick/nestjs-json-api#27]
Hi,

I have an entity class name `User`, now, the resource name generated is `/user/`
So if I want to generate to `/users`, I must rename the class name to `Users`

![Screen Shot 2023-01-01 at 10 24 06](https://user-images.githubusercontent.com/5398707/210160170-a4badc6b-2a15-4022-b6c6-c75c1b42e70a.png)

Have any options to override the resource to `users` with the entity class name `User` on your package @klerick?

Thanks

**Comment by klerick** [comment]
You can not change name of route. I don't have plane for add this feature

**Comment by too-soon** [comment]
@klerick Would you re-consider accepting this feature request if I try to come up with a solution for it and then open a PR?

I'm thinking about an option on our `JsonApi` decorator where you can overwrite what goes into the `Controller` decorator.

IE:

```ts
@JsonApi(User, {
  requiredSelectField: false,
  overrideEndpoint: 'users'
})
export class UserController extends JsonBaseController<User> {}
```

So we keep everything as is today but we would just have the option to change the endpoint path.

**Comment by klerick** [comment]
@Mites-G 
I have viewed source code, so now I believe will need to do minimal changes for this feature.

I think, it will be like that:

- [const decoratorOptions: DecoratorOptions](https://github.com/klerick/nestjs-json-api/blob/master/libs/json-api-nestjs/src/lib/mixin/module/module.mixin.ts#L76) = move up
- [Controller(`${camelToKebab(entityName)}`)(controllerClass); ](https://github.com/klerick/nestjs-json-api/blob/master/libs/json-api-nestjs/src/lib/mixin/module/module.mixin.ts#L51) need to chang:
```
Controller(decoratorOptions[' overrideEndpoint'] || `${camelToKebab(entityName)}`)(controllerClass);
```

**Comment by too-soon** [comment]
Awesome, @klerick. I was looking further into that and we reached the same conclusion.

Here's the pull request: https://github.com/klerick/nestjs-json-api/pull/43

Any more suggestions appreciated.

**Comment by klerick** [comment]
today I having weekend)but tomorrow, I will approve your pr and create new version.

**Comment by too-soon** [comment]
Enjoy your weekend!
