### ISSUE TITLE
EntityMetadataNotFoundError on posting entity with relation

### ISSUE THREAD

**Issue by SergeyTrifonov** [klerick/nestjs-json-api#28]
Hi,

I got an issue about using the library for entities with relations.

I have 2 entities:
```
@Entity()
export class Cable {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Armor)
    twistArmor: Armor;
}

@Entity()
export class Armor {
    @PrimaryGeneratedColumn()
    id: number;
}
```

When I was trying to add a new cable 
```
{
  "data": {
    "type": "cable",
    "attributes": {
      "name": "new one"
    },
    "relationships": {
      "twistArmor": {
        "data": {
          "type": "armor",
          "id": "1"
        }
      }
    }
  }
}
```

I got an error:
```
EntityMetadataNotFoundError: No metadata for "armor" was found.
```

As I see, all names are transformed using camelToKebab function, but when time comes to find relation data, name of repository aren't converted back.
https://github.com/klerick/nestjs-json-api/blob/daa9a9b87faedd65fbfa283e395584e4f6e188f0/libs/json-api-nestjs/src/lib/mixin/service/typeorm/utils/utils-methode.ts#L351

Could you help me solve this problem, please?
Thanks

**Comment by klerick** [comment]
Do you try to use "Armor" instead of "armor"?
camelToKebab use in transformation of result.
