### ISSUE TITLE
TypeError: metatype is not a constructor

### ISSUE THREAD

**Issue by too-soon** [klerick/nestjs-json-api#33]
Similar to #15, I'm getting this message when trying to use this library. I'm at a loss to what I'm missing.
I built a minimal reproduction in this repo: https://github.com/Mites-G/nestjs-jsonapi-minimal could you help me?

**Comment by klerick** [comment]
I believe the reason in incorrect resolve dependencies.
After command yarn, in node_modules the package 'ajv' has version 6.x.x, but the plugin need to vesion 8.x.x.
You will need correct resolve dependencies.

I do not use yarn, because, I can not help with it.

**Comment by too-soon** [comment]
Installing manually `yarn add ajv` makes it work. Thank you, @klerick!
