### ISSUE TITLE
Id types

### ISSUE THREAD

**Issue by alifey** [klerick/nestjs-json-api#5]
Hi, do IDs have to be numbers? What can i do other than change type so i can use another type e.g. uuid string.
(Optional: Is there a particular reason why ID types are numbers?)

**Comment by klerick** [comment]
oouch, indeed🤦, let me handle this

**Comment by alifey** [comment]
np, i thought it was a feature :)

**Comment by alifey** [comment]
with this, in "jsonapimodule.forRoot" global-prefix and imports parameters deprecated i guess

**Comment by klerick** [comment]
> with this, in "jsonapimodule.forRoot" global-prefix and imports parameters deprecated i guess

I have added import, this options is important.
global-prefix is deprecated, because NestJs have setGlobalPrefix method.
