### ISSUE TITLE
Including nested relationships

### ISSUE THREAD

**Issue by Michiel87** [klerick/nestjs-json-api#50]
First of all, your work on this project is much appreciated. Well done!

Are you planning to support dot separated includes, mentioned in the specification [here](https://jsonapi.org/format/#fetching-includes)?

This would allow us to include relationships of relationships. eg: 
`
GET /articles/1?include=comments.author 
`

In the example above our response would include comments related to articles and authors related to those comments.

**Comment by too-soon** [comment]
I agree that would be a nice feature to have. +1 on this.

Personally, I do not plan on working on this in the near future, but it's something I'd like to do when I have more free time.

@klerick, what do you think about this request?

**Comment by klerick** [comment]
I tried add this feature, at the beginning of the dev this plugin. It was very difficult. The plugin had many problem which difficult resolve. If allow nested include you can not predict database load.  I think current solution is good compromise between stability and  difficult
