### ISSUE TITLE
Question: Why dont you make an option this lib can work with prisma.

### ISSUE THREAD

**Issue by MingFEW** [klerick/nestjs-json-api#54]
Why dont you make an option this lib can work with prisma?

Thank you.

**Comment by too-soon** [comment]
This library works very closely to TypeORM so I doubt it would be possible.

Would probably be a better idea to create a new library inspired by this one but with Prisma (or ORM-agnostic) instead of TypeORM.

**Comment by klerick** [comment]
I will not have plan app support prisma. I tried use prisma and did not see any positive effect. For me TypeORM is better.

Now I am working for ACL solution which use json api plugin.
