### ISSUE TITLE
Create record not working

### ISSUE THREAD

**Issue by btibarra** [klerick/nestjs-json-api#68]
Hi, i'm starting a new project and have created some base records with a seeder. All the GET methods are working fine, index, single record, single record with relationships, relationship path, etc. 

The problem i'm having is when I do POST or PATCH methods, the server returns a status code 422 with the message: "Must have required property 'data'"

This is my POST data to http://localhost:3000/executives following the jsonapi:specs, i'm using Content-Type: application/vnd.api+json

```
{
  "data": {
    "type": "executives",
    "attributes": {
      "name": "Ember Hamster",
      "email": "ember@hamster.com",
      "localIdentifier": "1-9",
      "phoneNumber": "12345678910"
    }
  }
}
```

This is the code of the  Executives entity:
```
import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Customer } from '.';

@Entity({ name: 'executives' })
export class Executive {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: number;

  @Column({ name: 'local_identifier' })
  localIdentifier: string;

  @Column()
  name: string;

  @Column()
  email: string;

  @Column({ name: 'phone_number' })
  phoneNumber: string;

  @OneToMany(() => Customer, (customer) => customer.executive)
  customers: Customer[];
}
```

I tried with Postman and Insomnia, both POST and PATCH requests and the output is always the same 422 message. Maybe i'm missing some configuration to create or update a new record?

**Comment by klerick** [comment]
@btibarra [duplicate](https://github.com/klerick/nestjs-json-api/issues/10)

**Comment by klerick** [comment]
@btibarra [duplicate](https://github.com/klerick/nestjs-json-api/issues/10)
