### ISSUE TITLE
Cannot import Metadata for JSON_API_DECORATOR_ENTITY

### ISSUE THREAD

**Issue by hygison** [klerick/nestjs-json-api#71]
I am trying to get the TypeORM entity Dynamically from the controller into a pipe.

Basically I am doing: 
```ts
@JsonApi(Shop, {
	pipeForId: IdCheckPipe,
})
export class ShopController extends JsonBaseController<Shop> {
...
```
The pipe is being correctly applied. But I would like to pass the entity for such pipe.
So I thought about getting the entity from the metadata on this controller:
```
import { JSON_API_DECORATOR_ENTITY } from 'json-api-nestjs/src/lib/constants/reflection';
```

In order to use In my pipe do check if the user can access or not such item with the `id` they selected:
```ts
@Injectable()
export class IdCheckPipe implements PipeTransform {
	constructor(
		@Inject(REQUEST) private readonly request: Request,
		@InjectDataSource() private readonly connection: Connection,
		private readonly reflector: Reflector,
	) {}

	async transform(value: any, metadata: ArgumentMetadata) {
		const user: ActiveUserData = await this.request[REQUEST_USER_KEY];
		const entityClass = this.reflector.get<string>(JSON_API_DECORATOR_ENTITY, metadata.metatype);

		if (!entityClass) {
			throw new BadRequestException('Entity class not specified in metadata.');
		}
		try {
			await securityModifier(entityClass)?.canAccessId(user, value, this.connection);
		} catch (e) {
			throw new UnauthorizedException(`You do not have permission to access the id = ${value}`);
		}
		return value;
	}
}

```

The problem seems to be that I cannot import `JSON_API_DECORATOR_ENTITY`. Should it be allow me to export on the node modules or I should try something else? 
Because I get the following error:
```
Error: Package subpath './src/lib/constants/reflection' is not defined by "exports" in /usr/src/app/node_modules/json-api-nestjs/package.json
```

**Comment by klerick** [comment]
I believe, you try to use pipe incorrect. 
pipeForId - this it is options for check correct format data type. ex: for default I check for number, but you use in your db uuid.

so, You try to check permission. You should use [guard](https://docs.nestjs.com/guards) for this.
