### ISSUE TITLE
Transform Body On post

### ISSUE THREAD

**Issue by hygison** [klerick/nestjs-json-api#80]
I would like to transform the body of the request.

For example I have: 

```ts
@Roles(UserRoles.OWNER)
@Post()
async postOne(@Body() body: ResourceRequestObject<Restaurant>['data']) {
  return await this.serviceMixin.postOne({ body: body });
}
```
Lets day my Restaurant Entity has like id, name, userId, address, createdAt, updatedAt, deletedAt.

I would like to force the body to change. Because I am not exposing the `userId`, the user does not know it should add the userId, can I do that in a Pipe inside the `@Body()` decorator? Like: 

```ts
@Roles(UserRoles.OWNER)
@Post()
async postOne(@Body(AddUserIdToRestaurantPipe) body: ResourceRequestObject<Restaurant>['data']) {
  return await this.serviceMixin.postOne({ body: body });
}
```

I would like to make this in a pipe, because this is only for the postOne, in case of postRel I would also need a different one, and so on, so basically all of them a different method.
Would this be the way you design to be done? Because When I try using the pipe inside the body as you saw above, it does not get loaded.

**Comment by klerick** [comment]
@hygison What version of json-api do you use? In latest version has this function. You can see example [here](https://github.com/klerick/nestjs-json-api/blob/master/apps/json-api-server/src/app/resources/controllers/extend-user/extend-user.controller.ts#L63):

and here you can see example [pipe](https://github.com/klerick/nestjs-json-api/blob/master/apps/json-api-server/src/app/resources/service/example.pipe.ts)

[here](https://github.com/klerick/nestjs-json-api/blob/master/libs/json-api/json-api-nestjs/src/lib/helper/bind-controller.spec.ts#L116) you can see test for your point
