### ISSUE TITLE
How to implement IsNull and IsNotNull in filter?

### ISSUE THREAD

**Issue by ixxvivxxi** [klerick/nestjs-json-api#81]
I would like to filter mainly columns something like this:
```
filter: {
  startDate: {
    isNull: true
  },
  endDate: {
    isNotNull: true
  }
}
```

Perhaps there is a way to add your own filters, but I haven’t figured out how

**Comment by klerick** [comment]
@ixxvivxxi 
try to use [filter operator](https://github.com/klerick/nestjs-json-api/tree/master/libs/json-api/json-api-nestjs#filter-operand) **eq** and **ne**
example: 
`http://localhost:3000/api/users?filter%5BfirstName%5D[eq]=null&filter%5Blogin%5D[ne]=null` 
is equal of sql query:

 `SELECT * FROM "users" "Users" WHERE "Users"."login" <> null AND "Users"."first_name" = null`
 
 so you filter should be:
```
 filter: {
  startDate: {
    eq: true
  },
  endDate: {
    no: true
  }
}
```

**Comment by ixxvivxxi** [comment]
@klerick Thank you for your response! But your example doesn't work, there is a message - `String should be as date`
`{code: "custom", message: "String should be as date", path: ["filter", "target", "startDate", "eq"]}`
`{code: "custom", message: "String should be as date", path: ["filter", "target", "endDate", "ne"]}`

**Comment by klerick** [comment]
@ixxvivxxi 
Oooops) 
this is bug of validation)
I will try fixed it ASAP

**Comment by klerick** [comment]
@ixxvivxxi 
try to use version [json-api-nestjs@7.0.1](https://www.npmjs.com/package/json-api-nestjs/v/7.0.1)

**Comment by ixxvivxxi** [comment]
Thank you! The issue was fixed
