### ISSUE TITLE
Cannot patch a resource relationship without providing base attributes

### ISSUE THREAD

**Issue by ajcobo** [klerick/nestjs-json-api#84]
I'm trying to update a relationship, without providing attributes to the base resource.

According to the [jsonapi spec](https://jsonapi.org/format/#crud-updating-resource-relationships), this should be possible.

This is relevant when you want to change many relationships at once. You always have the alternative to patch the specific relationship however, using its route.

The request
`/customer-bank-accounts/1`
```
{
    "data": {
        "id": "1",
        "type": "customer-bank-accounts",
        "relationships": {
            "bank": {
                "data": {
                    "type": "banks",
                    "id": "2"
                }
            }
        }
    }
}
```

The current response

```
{
	"status": 422,
	"errors": [
		{
			"source": {
				"parameter": "/data"
			},
			"detail": "Must have required property 'attributes'"
		}
	]
}
```

**Comment by klerick** [comment]
@ajcobo has been fixed
You could to try use new [version](https://www.npmjs.com/package/json-api-nestjs/v/7.0.2)
