### ISSUE TITLE
Resource Relationship not allowing data key.

### ISSUE THREAD

**Issue by btibarra** [klerick/nestjs-json-api#87]
Hello, since version 7.0.2, the POST and PATCH methods of resources with relationships don't allow the `data` object.
It requires the content of data instead.

https://jsonapi.org/format/#crud-creating
https://jsonapi.org/format/#crud-updating-resource-relationships

Notice in both cases the structure of the json is:
```
{
  "data": {
    ... ,
    "relationships": {
      "person": {
        "data": { 
            "type": "people", 
             "id": "9"
        }
      }
    }
  }
}
```

And in version 7.0.2, it expects this structure:
```
{
  "data": {
    ... ,
    "relationships": {
      "person": {
        "type": "people", 
        "id": "9" 
      }
    }
  }
}
```

**Comment by klerick** [comment]
fixed: https://www.npmjs.com/package/json-api-nestjs/v/7.0.3
