### ISSUE TITLE
Swagger POST and PATCH not showing Request body "Unknown Type: object"

### ISSUE THREAD

**Issue by hygison** [klerick/nestjs-json-api#91]
The problem I get is only for the POST and PATCH, I cannot see the proper Request Body. 
I get the following result on the swagger:

<img width="512" alt="patch-1" src="https://github.com/user-attachments/assets/e98f2be2-7a58-480b-a3f7-62e6678f7b9e">

When I open the schema I see this: 

<img width="1425" alt="schema" src="https://github.com/user-attachments/assets/446f3185-1803-4403-a179-f9e2d85213d6">

The example above was PATCH, but the POST has the same problem.
Is there anything wrong in my configurations or something wrong with the way I am doing that I cannot do anymore in the new version? 

How can I see the proper POST/PATCH request body?

I just updated the version of json-api-nestjs to ` "json-api-nestjs": "^7.0.3",`  and NestSwagger: ` "@nestjs/swagger": "^7.4.2",`. 
I am getting a problem with Swagger on this version. When I was using ` "json-api-nestjs": "^6.0.2",`, the exact code below was working fine for me.

```ts
const app = await NestFactory.create(AppModule);

const config = new DocumentBuilder()
  .setTitle('JSON API swagger example')
  .setDescription('The JSON API list example')
  .setVersion('3.0')
  .build();

SwaggerModule.setup(
  'swagger',
  app,
  () => SwaggerModule.createDocument(app, config), // !!!Important: document as factory
  {}
);
``` 

I copy this from the [npm docs](https://www.npmjs.com/package/json-api-nestjs)

**Comment by klerick** [comment]
@hygison could you show entity of Sale?

**Comment by hygison** [comment]
My sale entity is:
```ts
@Entity({ name: 'sales' })
export class Sale extends CoreEntity {
  constructor(obj = {}) {
    super();
    Object.assign(this, obj);
  }

  @Column({ type: 'varchar', name: 'created_by_user_id', nullable: true })
  createdByUserId?: string | null;

  @ManyToOne(() => User, (e) => e.sales, { onDelete: 'NO ACTION', nullable: true })
  @JoinColumn({ name: 'created_by_user_id', referencedColumnName: 'id' })
  createdByUser?: User | null;

  @Index()
  @Column({ type: 'varchar', name: 'artwork_id', nullable: true })
  artworkId?: string | null;

  @ManyToOne(() => Artwork, (e) => e.sales, { onDelete: 'NO ACTION', nullable: true })
  @JoinColumn({ name: 'artwork_id', referencedColumnName: 'id' })
  artwork?: Artwork | null;

  @Column({ type: 'int' })
  type: SalesType;

  @Column({ type: 'varchar', nullable: true, unique: true, name: 'transaction_hash' })
  createdTransactionHash?: string;

  @Column({ type: 'int', nullable: true, name: 'listing_id', unique: true })
  listingId?: number;

  @Column({ type: 'int' })
  status: SalesStatus;

  @Column({ type: 'timestamp', nullable: true, name: 'expires_at' })
  expiresAt: Date | null;

  @OneToMany(() => Bid, (e) => e.sale, { onDelete: 'NO ACTION', nullable: true })
  bids?: Bid[] | null;

  isExpired(): boolean {
    return this.expiresAt ? isBefore(this.expiresAt, new Date()) : false;
  }
}
```

I did try the same with less complex entities:
```ts
@Entity()
@Unique(['type', 'userId'])
export class Sns extends CoreEntity {
  constructor(obj = {}) {
    super();
    Object.assign(this, obj);
  }

  @MaxLength(255)
  @Column({ type: 'varchar', length: 255 })
  username: string;

  @Column({ type: 'int' })
  type: SnsType;

  @Column({ type: 'bigint', unsigned: true, name: 'user_id' })
  userId: string;
}
```

And the same happens. 
My CoreEntity is

```ts
export class CoreEntity {
  @PrimaryGeneratedColumn({ type: 'bigint', unsigned: true })
  readonly id?: string;

  @CreateDateColumn({ name: 'created_at' })
  readonly createdAt?: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  readonly updatedAt?: Date;

  @DeleteDateColumn({ name: 'deleted_at', nullable: true })
  readonly deletedAt?: Date | null;
}
```

My nest-cli.json:
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/swagger",
        "options": {
          "dtoFileNameSuffix": [".entity.ts", ".dto.ts"],
          "controllerFileNameSuffix": [".controller.ts"],
          "classValidatorShim": true,
          "dtoKeyOfComment": "description",
          "controllerKeyOfComment": "description",
          "introspectComments": true
        }
      }
    ]
  }
}

```

**Comment by klerick** [comment]
@hygison
Could you do some changes for check?
Could you change this file: node_modules/json-api-nestjs/src/lib/helper/zod/zod-input-post-schema/attributes.js 

after 
```
case orm_1.TypeField.string:
zodShema = zod_1.z.string().optional();
break;
```

need add:

```
case orm_1.TypeField.object:
zodShema = zod_1.z.object({}).passthrough();
break;
```
if everything is ok, I push new version.

**Comment by hygison** [comment]
If that is the only change, it was not enough to fix. 
I still get the same exactly described result.

**Comment by klerick** [comment]
@hygison 
I can't reproduce this problem. Could you create example repo with this problem?

**Comment by hygison** [comment]
HERE: https://github.com/hygison/json-api-usage
I made 3 simple endpoints:
<img width="338" alt="Screenshot 2024-10-07 at 16 13 26" src="https://github.com/user-attachments/assets/060511e3-7a37-41c5-a790-c0b60dcf03cf">

In all of them I notice the bud described: 
| Header | Header | Header |
|--------|--------|--------|
| <img width="403" alt="Screenshot 2024-10-07 at 16 14 39" src="https://github.com/user-attachments/assets/ff391ac9-8c42-43b7-86bb-b65ce2374719"> | <img width="366" alt="Screenshot 2024-10-07 at 16 15 21" src="https://github.com/user-attachments/assets/86ad9ae2-0d0c-4ecf-82f4-539e137c7e48"> | <img width="519" alt="Screenshot 2024-10-07 at 16 15 56" src="https://github.com/user-attachments/assets/0c9f22fe-fd70-4881-824d-2b3d83bf6df8"> |

**Comment by klerick** [comment]
the problem in other side.
I using [@anatine/zod-openapi](https://github.com/anatine/zod-plugins/tree/main/packages/zod-openapi) for convert zod to openApi, but in new version this module work [with open api v3.1 ](https://github.com/anatine/zod-plugins/issues/191)
but @nestjs/swagger generate [v3.0 by default](https://github.com/nestjs/swagger/blob/master/lib/fixtures/document.base.ts)

so, solution for you:
you can rallback to v2.2.3 of @anatine/zod-openapi or you can change [version schema manual](https://github.com/nestjs/swagger/issues/2361#issuecomment-2018406870)

**Comment by hygison** [comment]
Just to keep documented here. I could solve doing the updating the version of the @nestjs/swagger : `"@nestjs/swagger": "^11.0.3"` and openapi to 3.1.0

The pr for this was made here: https://github.com/hygison/json-api-usage/pull/1

package.json:
```
"@nestjs/swagger": "^11.0.3"
```


Swagger Document Builder: 
```ts
  const config = new DocumentBuilder()
    .setOpenAPIVersion('3.1.0')
    .setTitle('Docs Swagger')
    .setVersion('1.0.0')
    .addBearerAuth()
    .build();
```

**Comment by klerick** [comment]
I am updating nestjs after adaptive microorm
